fix: fixed test "Block user in conversation list"
oxen-io/session-playwright pull request #19
Opened 2024-09-11 23:22 UTC by Bilb

2024-09-16 03:52 UTC, burtonemily commented on tests/automation/group_testing.spec.ts
> +        .withArgs({ name: shortenWithBrackets(dracula.accountid) })
I'll definitely be stealing this function for Appium

2024-09-16 06:02 UTC, burtonemily requested changes
Made some comments

2024-09-16 06:24 UTC, Bilb commented on tests/automation/linked_device_group.spec.ts
>      // Control-message needs to be changed to group-update-message (on disappearing messages branch)
yes, removed here and in 2 other places

2024-09-16 06:24 UTC, Bilb commented on tests/automation/utilities/utils.ts
> -export async function typeIntoInputSlow(
wasn't needed. The other one is doing just fine

2024-09-17 03:58 UTC, burtonemily approved these changes

2024-09-17 04:09 UTC, merged